/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/UI/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppEmpty: typeof import('./src/components/UI/AppEmpty.vue')['default']
    AppError: typeof import('./src/components/UI/AppError.vue')['default']
    AppFooter: typeof import('./src/components/core/AppFooter.vue')['default']
    AppFormItem: typeof import('./src/components/UI/AppFormItem.vue')['default']
    AppHeader: typeof import('./src/components/core/AppHeader.vue')['default']
    AppImageUpload: typeof import('./src/components/UI/AppImageUpload.vue')['default']
    AppInput: typeof import('./src/components/UI/AppInput.vue')['default']
    AppSkeleton: typeof import('./src/components/UI/AppSkeleton.vue')['default']
    AppSpinner: typeof import('./src/components/UI/AppSpinner.vue')['default']
    CarBaseBlock: typeof import('./src/components/CarBaseBlock.vue')['default']
    CarCard: typeof import('./src/components/CarCard.vue')['default']
    CarEditCard: typeof import('./src/components/CarEditCard.vue')['default']
    CarExtended: typeof import('./src/components/CarExtended.vue')['default']
    CarExtendedBlock: typeof import('./src/components/CarExtendedBlock.vue')['default']
    CarImageBlock: typeof import('./src/components/CarImageBlock.vue')['default']
    'IFluent:boxSearch20Regular': typeof import('~icons/fluent/box-search20-regular')['default']
    'IFluent:dismiss24Regular': typeof import('~icons/fluent/dismiss24-regular')['default']
    'IFluent:dismissCircle24Regular': typeof import('~icons/fluent/dismiss-circle24-regular')['default']
    'IFluent:person20Regular': typeof import('~icons/fluent/person20-regular')['default']
    'IGravityUi:arrowRight': typeof import('~icons/gravity-ui/arrow-right')['default']
    'IGravityUi:pencil': typeof import('~icons/gravity-ui/pencil')['default']
    'IIon:close': typeof import('~icons/ion/close')['default']
    'IIon:closeOutline': typeof import('~icons/ion/close-outline')['default']
    'IIon:cloudUploadOutline': typeof import('~icons/ion/cloud-upload-outline')['default']
    'IMaterialSymbols:errorOutlineRounded': typeof import('~icons/material-symbols/error-outline-rounded')['default']
    'IMaterialSymbols:errorRounded': typeof import('~icons/material-symbols/error-rounded')['default']
    'IMaterialSymbolsLight:autoTransmissionOutline': typeof import('~icons/material-symbols-light/auto-transmission-outline')['default']
    'IMaterialSymbolsLight:infoOutline': typeof import('~icons/material-symbols-light/info-outline')['default']
    'IMaterialSymbolsLight:localGasStation': typeof import('~icons/material-symbols-light/local-gas-station')['default']
    'IMaterialSymbolsLight:refresh': typeof import('~icons/material-symbols-light/refresh')['default']
    'IMaterialSymbolsLight:speed': typeof import('~icons/material-symbols-light/speed')['default']
    'IMaterialSymbolsLight:straighten': typeof import('~icons/material-symbols-light/straighten')['default']
    'IMdi:loading': typeof import('~icons/mdi/loading')['default']
    'IPh:engine': typeof import('~icons/ph/engine')['default']
    'IPh:engineBold': typeof import('~icons/ph/engine-bold')['default']
    'IPh:image': typeof import('~icons/ph/image')['default']
    'ISi:errorDuotone': typeof import('~icons/si/error-duotone')['default']
    'ISvgSpinners:180Ring': typeof import('~icons/svg-spinners/180-ring')['default']
    'ISvgSpinners:barsRotateFade': typeof import('~icons/svg-spinners/bars-rotate-fade')['default']
    'ISystemUicons:boxOpen': typeof import('~icons/system-uicons/box-open')['default']
    'ITabler:car': typeof import('~icons/tabler/car')['default']
    'ITabler:cloudUpload': typeof import('~icons/tabler/cloud-upload')['default']
    'ITabler:error404': typeof import('~icons/tabler/error404')['default']
    'ITabler:faceIdError': typeof import('~icons/tabler/face-id-error')['default']
    NotFound: typeof import('./src/components/UI/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
